### PR TITLE
Automatic .env file generation

### PR DESCRIPTION
**Pull request by parruc**
Also added changes and readme lines

### CODE REVIEW

**Comment by nazrulworld** [comment]
@parruc thank you so much for your nice work. 
Minor things: 1. we saw flake8 error in Travis, can you please fix.
2. if possible add a test for .env file.

Although if you want, I can do those but may be better if you do,

**Comment by parruc** [comment]
I'm a little under pressure at work these days and the time is an issue.
I'll do in the next few weeks if you don't do it before, sorry for the
"raw" job but I needed it working asap.

Il lun 27 mag 2019, 18:55 Md Nazrul Islam <notifications@github.com> ha
scritto:

**Comment by parruc** [comment]
Managed to squeeze some time. Hope you will release it soon ^_^

Added new python .env file generation test
Fixed isort-path test that failed on my build.
Fixed flake8 errror (it appears we had different line length setup)

**Comment by nazrulworld** [comment]
Thanks at lot @parruc , hope we are going to do new release soon.

**Pull request merged**
