### PR TITLE
add in languageserver and analysis.extraPaths settings for pylance

### PR DESCRIPTION
**Pull request by djay**

### CODE REVIEW

**Comment by nazrulworld** [comment]
@djay thank you so much for your great works. Can you please update the changes log, then will go-ahead for a new release.

**Comment by djay** [comment]
@nazrulworld done. but I think you should include both PRs in a release. #9 enables set and forget on all your buildouts automatically.

**Comment by nazrulworld** [comment]
@djay after merging #9 see conflicts in those files, can you please resolve.

**Comment by djay** [comment]
done

**Comment by djay** [comment]
@nazrulworld going to release it?

**Comment by nazrulworld** [comment]
@djay yes, will do soon, but if you have more changes, I can wait :)

**Comment by nazrulworld** [comment]
https://pypi.org/project/collective.recipe.vscode/0.1.6/ here we go

**Pull request merged**
